New resources added
The-Art-of-Hacking/h4cker pull request #176
Opened 2023-09-28 17:41 UTC by d3xt3r7

2023-09-28 17:41 UTC, d3xt3r7 commented
Allow me to contribute in this repoitory.

2023-10-03 04:18 UTC, santosomar commented
Regrettably, a number of resources incorporated in this pull request appear to infringe upon copyrights from various sources. Therefore, I am unable to approve this pull request at this time.

2023-10-03 04:21 UTC, santosomar reviewed
Regrettably, a number of resources incorporated in this pull request appear to infringe upon copyrights from various sources.

2023-10-03 04:21 UTC, santosomar commented on Red-Team-Operations.md
This one is a good resource and does not infringe copyrights.

2023-10-03 04:21 UTC, santosomar commented on Free Paid Courses/Links.md
Regrettably, a number of resources incorporated in this pull request appear to infringe upon copyrights from various sources.

2023-10-03 04:22 UTC, santosomar reviewed
Regrettably, a number of resources incorporated in this pull request appear to infringe upon copyrights from various sources.

2023-10-03 04:23 UTC, santosomar requested changes
Please remove all the links that violate copyrights.

2023-10-03 05:51 UTC, dx7er commented on Red-Team-Operations.md
I have taken resources from GitHub and wanted to use it in this repository. There shouldn't be any copyright issue.

2023-10-03 05:52 UTC, closed without merging